### ISSUE TITLE
Support optional task creation date

### ISSUE THREAD

**Issue by ferki** [owenh000/todo.txt-cli-dorecur#1]
First, thank you for this project, @owenh000! :pray: 

I'm using the optional creation dates in my `todo.txt` file, but `todo.txt-cli-dorecur` doesn't seem to like them out of the box.

It treats the original creation date as part of the full task text, so when calling `dorecur.py` the newly created task still has its original creation date on top of the new creation date, e.g.:

```
(B) 2021-11-07 my task rec:+1m due:2021-12-10 t:2021-12-01
```

becomes

```
(B) 2021-12-06 2021-11-07 my task rec:+1m due:2022-01-10 t:2022-01-01
```

while I'd expect

```
(B) 2021-12-06 my task rec:+1m due:2022-01-10 t:2022-01-01
```

I'll try to send a PR about fixing it soon.

**Comment by owenh000** [comment]
Yeah, I don't use creation dates, so I never noticed this problem. Thanks for reporting and I'll go look at that pull request now.

**Comment by owenh000** [comment]
Looks good to me! It's merged now! Thank you for your contribution.

**Comment by ferki** [comment]
Great! :tada: Thanks for the review and merge :+1:
