### ISSUE TITLE
SyntaxWarning on use

### ISSUE THREAD

**Issue by mgiugliano** [owenh000/todo.txt-cli-dorecur#4]
Thanks really a lot for this "action". I would like to report that it throws the following SyntaxWarning on its use:

```
/Users/XXX/.todo/.todo.actions.d/do:241: SyntaxWarning: invalid escape sequence '\('
  line = re.sub("^(?P<pri>\([A-Z]\) )?\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ", "\g<pri>", line)
/Users/XXX/.todo/.todo.actions.d/do:241: SyntaxWarning: invalid escape sequence '\g'
  line = re.sub("^(?P<pri>\([A-Z]\) )?\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ", "\g<pri>", line)
```

I would be happy to dig further to solve it, as it might be a Python-related change.

**Comment by owenh000** [comment]
Does it work now, with commit 0e7eeb15db2a2e124e4e8272314c7ec6ef99f48b?

**Comment by mgiugliano** [comment]
It works! I am not a Python expert and my addition of ```r""``` was not enough. Your change suppressed the warnings.

Thanks again for your work.

**Comment by owenh000** [comment]
>my addition of `r""` was not enough

That is all that was really necessary, though it probably is needed for *both* of the strings, like this:

`line = re.sub(r"^(?P<pri>\([A-Z]\) )?\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ", r"\g<pri>", line)`

The other changes were not related really, they were just to wrap the long line. I turned on the `re.VERBOSE` flag so the first string/pattern could be split onto multiple lines and then had to escape the two spaces with backslashes so they wouldn't be ignored.

>Thanks again for your work.

You're welcome.
